services:
  app:
    build: .
    image: ${APP_NAME}-app:latest
    container_name: ${APP_NAME}-app
    depends_on:
      - postgres
    ports:
      - "${PORT}:8080"
    environment:
      - PORT=${PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PORT=${DB_PORT}
      - DB_HOST=postgres

  postgres:
    image: postgres:latest
    container_name: ${APP_NAME}-db
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data
      - ./init-db/:/docker-entrypoint-initdb.d/

volumes:
  postgres-volume:
    name: ${APP_NAME}-db-volume
