services:
  postgres:
    image: postgres:latest
    container_name: ${APP_NAME}-db
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - /home/${USER}/${APP_NAME}:/var/lib/postgresql/repositories
